version: '3'
services:
  node:
    build:
      context: ./my-remix-app
      dockerfile: Dockerfile
    volumes:
      - ./my-remix-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
